TRUNCATE TABLE User
TRUNCATE TABLE Exercise
TRUNCATE TABLE UserExercise
TRUNCATE TABLE Tag
TRUNCATE TABLE ExerciseTags
TRUNCATE TABLE Emotion
TRUNCATE TABLE Thought
TRUNCATE TABLE Behavior
TRUNCATE TABLE EmotionTags
TRUNCATE TABLE ThoughtTags
TRUNCATE TABLE BehaviorTags
TRUNCATE TABLE InputForm
TRUNCATE TABLE InputFormEmotions TRUNCATE TABLE InputFormThoughts TRUNCATE TABLE InputFormBehaviors
